export type AmenityType =
  | 'wifi'
  | 'ar-condicionado'
  | 'garagem'
  | 'cozinha-equipada'
  | 'smart-tv'
  | 'lavadora'
  | 'piscina'
  | 'churrasqueira'
  | 'varanda'
  | 'vista-mar'
  | 'academia'
  | 'jacuzzi'
  | 'lareira'
  | 'aquecimento'
  | 'pet-friendly'
